-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Aihealue CASCADE;
DROP TABLE IF EXISTS Keskustelu CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Luettu CASCADE;